import { KanaCharacter, KanaCategory } from '@/types/kana';
import { Locale } from '@/types/common';
export const KANA_DATA: KanaCharacter[] = [
  { id: 'a', hiragana: 'あ', katakana: 'ア', romaji: 'a', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'i', hiragana: 'い', katakana: 'イ', romaji: 'i', category: KanaCategory.SEION, difficulty: 1, strokeCount: 2 },
  { id: 'u', hiragana: 'う', katakana: 'ウ', romaji: 'u', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'e', hiragana: 'え', katakana: 'エ', romaji: 'e', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'o', hiragana: 'お', katakana: 'オ', romaji: 'o', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'ka', hiragana: 'か', katakana: 'カ', romaji: 'ka', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'ki', hiragana: 'き', katakana: 'キ', romaji: 'ki', category: KanaCategory.SEION, difficulty: 1, strokeCount: 4 },
  { id: 'ku', hiragana: 'く', katakana: 'ク', romaji: 'ku', category: KanaCategory.SEION, difficulty: 1, strokeCount: 2 },
  { id: 'ke', hiragana: 'け', katakana: 'ケ', romaji: 'ke', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'ko', hiragana: 'こ', katakana: 'コ', romaji: 'ko', category: KanaCategory.SEION, difficulty: 1, strokeCount: 2 },
  { id: 'sa', hiragana: 'さ', katakana: 'サ', romaji: 'sa', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'shi', hiragana: 'し', katakana: 'シ', romaji: 'si', category: KanaCategory.SEION, difficulty: 2, strokeCount: 3 },
  { id: 'su', hiragana: 'す', katakana: 'ス', romaji: 'su', category: KanaCategory.SEION, difficulty: 1, strokeCount: 2 },
  { id: 'se', hiragana: 'せ', katakana: 'セ', romaji: 'se', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'so', hiragana: 'そ', katakana: 'ソ', romaji: 'so', category: KanaCategory.SEION, difficulty: 1, strokeCount: 2 },
  { id: 'ta', hiragana: 'た', katakana: 'タ', romaji: 'ta', category: KanaCategory.SEION, difficulty: 1, strokeCount: 4 },
  { id: 'chi', hiragana: 'ち', katakana: 'チ', romaji: 'chi', category: KanaCategory.SEION, difficulty: 2, strokeCount: 3 },
  { id: 'tsu', hiragana: 'つ', katakana: 'ツ', romaji: 'tsu', category: KanaCategory.SEION, difficulty: 2, strokeCount: 3 },
  { id: 'te', hiragana: 'て', katakana: 'テ', romaji: 'te', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'to', hiragana: 'と', katakana: 'ト', romaji: 'to', category: KanaCategory.SEION, difficulty: 1, strokeCount: 2 },
  { id: 'na', hiragana: 'な', katakana: 'ナ', romaji: 'na', category: KanaCategory.SEION, difficulty: 1, strokeCount: 4 },
  { id: 'ni', hiragana: 'に', katakana: 'ニ', romaji: 'ni', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'nu', hiragana: 'ぬ', katakana: 'ヌ', romaji: 'nu', category: KanaCategory.SEION, difficulty: 2, strokeCount: 3 },
  { id: 'ne', hiragana: 'ね', katakana: 'ネ', romaji: 'ne', category: KanaCategory.SEION, difficulty: 2, strokeCount: 4 },
  { id: 'no', hiragana: 'の', katakana: 'ノ', romaji: 'no', category: KanaCategory.SEION, difficulty: 1, strokeCount: 1 },
  { id: 'ha', hiragana: 'は', katakana: 'ハ', romaji: 'ha', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'hi', hiragana: 'ひ', katakana: 'ヒ', romaji: 'hi', category: KanaCategory.SEION, difficulty: 1, strokeCount: 2 },
  { id: 'fu', hiragana: 'ふ', katakana: 'フ', romaji: 'hu', category: KanaCategory.SEION, difficulty: 2, strokeCount: 4 },
  { id: 'he', hiragana: 'へ', katakana: 'ヘ', romaji: 'he', category: KanaCategory.SEION, difficulty: 1, strokeCount: 1 },
  { id: 'ho', hiragana: 'ほ', katakana: 'ホ', romaji: 'ho', category: KanaCategory.SEION, difficulty: 1, strokeCount: 4 },
  { id: 'ma', hiragana: 'ま', katakana: 'マ', romaji: 'ma', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'mi', hiragana: 'み', katakana: 'ミ', romaji: 'mi', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'mu', hiragana: 'む', katakana: 'ム', romaji: 'mu', category: KanaCategory.SEION, difficulty: 2, strokeCount: 3 },
  { id: 'me', hiragana: 'め', katakana: 'メ', romaji: 'me', category: KanaCategory.SEION, difficulty: 2, strokeCount: 2 },
  { id: 'mo', hiragana: 'も', katakana: 'モ', romaji: 'mo', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'ya', hiragana: 'や', katakana: 'ヤ', romaji: 'ya', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'yu', hiragana: 'ゆ', katakana: 'ユ', romaji: 'yu', category: KanaCategory.SEION, difficulty: 2, strokeCount: 3 },
  { id: 'yo', hiragana: 'よ', katakana: 'ヨ', romaji: 'yo', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'ra', hiragana: 'ら', katakana: 'ラ', romaji: 'ra', category: KanaCategory.SEION, difficulty: 2, strokeCount: 2 },
  { id: 'ri', hiragana: 'り', katakana: 'リ', romaji: 'ri', category: KanaCategory.SEION, difficulty: 1, strokeCount: 2 },
  { id: 'ru', hiragana: 'る', katakana: 'ル', romaji: 'ru', category: KanaCategory.SEION, difficulty: 2, strokeCount: 2 },
  { id: 're', hiragana: 'れ', katakana: 'レ', romaji: 're', category: KanaCategory.SEION, difficulty: 1, strokeCount: 1 },
  { id: 'ro', hiragana: 'ろ', katakana: 'ロ', romaji: 'ro', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'wa', hiragana: 'わ', katakana: 'ワ', romaji: 'wa', category: KanaCategory.SEION, difficulty: 1, strokeCount: 3 },
  { id: 'wo', hiragana: 'を', katakana: 'ヲ', romaji: 'wo', category: KanaCategory.SEION, difficulty: 3, strokeCount: 3 },
  { id: 'n', hiragana: 'ん', katakana: 'ン', romaji: 'n', category: KanaCategory.SEION, difficulty: 1, strokeCount: 1 },
  { id: 'ga', hiragana: 'が', katakana: 'ガ', romaji: 'ga', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 5 },
  { id: 'gi', hiragana: 'ぎ', katakana: 'ギ', romaji: 'gi', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 6 },
  { id: 'gu', hiragana: 'ぐ', katakana: 'グ', romaji: 'gu', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 4 },
  { id: 'ge', hiragana: 'げ', katakana: 'ゲ', romaji: 'ge', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 5 },
  { id: 'go', hiragana: 'ご', katakana: 'ゴ', romaji: 'go', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 4 },
  { id: 'za', hiragana: 'ざ', katakana: 'ザ', romaji: 'za', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 5 },
  { id: 'ji', hiragana: 'じ', katakana: 'ジ', romaji: 'zi', category: KanaCategory.DAKUON, difficulty: 3, strokeCount: 5 },
  { id: 'zu', hiragana: 'ず', katakana: 'ズ', romaji: 'zu', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 4 },
  { id: 'ze', hiragana: 'ぜ', katakana: 'ゼ', romaji: 'ze', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 5 },
  { id: 'zo', hiragana: 'ぞ', katakana: 'ゾ', romaji: 'zo', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 4 },
  { id: 'da', hiragana: 'だ', katakana: 'ダ', romaji: 'da', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 6 },
  { id: 'dji', hiragana: 'ぢ', katakana: 'ヂ', romaji: 'di', category: KanaCategory.DAKUON, difficulty: 3, strokeCount: 5 },
  { id: 'dzu', hiragana: 'づ', katakana: 'ヅ', romaji: 'du', category: KanaCategory.DAKUON, difficulty: 3, strokeCount: 5 },
  { id: 'de', hiragana: 'で', katakana: 'デ', romaji: 'de', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 5 },
  { id: 'do', hiragana: 'ど', katakana: 'ド', romaji: 'do', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 4 },
  { id: 'ba', hiragana: 'ば', katakana: 'バ', romaji: 'ba', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 5 },
  { id: 'bi', hiragana: 'び', katakana: 'ビ', romaji: 'bi', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 4 },
  { id: 'bu', hiragana: 'ぶ', katakana: 'ブ', romaji: 'bu', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 6 },
  { id: 'be', hiragana: 'べ', katakana: 'ベ', romaji: 'be', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 3 },
  { id: 'bo', hiragana: 'ぼ', katakana: 'ボ', romaji: 'bo', category: KanaCategory.DAKUON, difficulty: 2, strokeCount: 6 },
  { id: 'pa', hiragana: 'ぱ', katakana: 'パ', romaji: 'pa', category: KanaCategory.HANDAKUON, difficulty: 2, strokeCount: 5 },
  { id: 'pi', hiragana: 'ぴ', katakana: 'ピ', romaji: 'pi', category: KanaCategory.HANDAKUON, difficulty: 2, strokeCount: 4 },
  { id: 'pu', hiragana: 'ぷ', katakana: 'プ', romaji: 'pu', category: KanaCategory.HANDAKUON, difficulty: 2, strokeCount: 6 },
  { id: 'pe', hiragana: 'ぺ', katakana: 'ペ', romaji: 'pe', category: KanaCategory.HANDAKUON, difficulty: 2, strokeCount: 3 },
  { id: 'po', hiragana: 'ぽ', katakana: 'ポ', romaji: 'po', category: KanaCategory.HANDAKUON, difficulty: 2, strokeCount: 6 },
  { id: 'kya', hiragana: 'きゃ', katakana: 'キャ', romaji: 'kya', category: KanaCategory.YOON, difficulty: 3, strokeCount: 7 },
  { id: 'kyu', hiragana: 'きゅ', katakana: 'キュ', romaji: 'kyu', category: KanaCategory.YOON, difficulty: 3, strokeCount: 7 },
  { id: 'kyo', hiragana: 'きょ', katakana: 'キョ', romaji: 'kyo', category: KanaCategory.YOON, difficulty: 3, strokeCount: 7 },
  { id: 'sha', hiragana: 'しゃ', katakana: 'シャ', romaji: 'sya', category: KanaCategory.YOON, difficulty: 3, strokeCount: 6 },
  { id: 'shu', hiragana: 'しゅ', katakana: 'シュ', romaji: 'syu', category: KanaCategory.YOON, difficulty: 3, strokeCount: 6 },
  { id: 'sho', hiragana: 'しょ', katakana: 'ショ', romaji: 'syo', category: KanaCategory.YOON, difficulty: 3, strokeCount: 6 },
  { id: 'cha', hiragana: 'ちゃ', katakana: 'チャ', romaji: 'cya', category: KanaCategory.YOON, difficulty: 3, strokeCount: 6 },
  { id: 'chu', hiragana: 'ちゅ', katakana: 'チュ', romaji: 'cyu', category: KanaCategory.YOON, difficulty: 3, strokeCount: 6 },
  { id: 'cho', hiragana: 'ちょ', katakana: 'チョ', romaji: 'cyo', category: KanaCategory.YOON, difficulty: 3, strokeCount: 6 },
  { id: 'nya', hiragana: 'にゃ', katakana: 'ニャ', romaji: 'nya', category: KanaCategory.YOON, difficulty: 3, strokeCount: 6 },
  { id: 'nyu', hiragana: 'にゅ', katakana: 'ニュ', romaji: 'nyu', category: KanaCategory.YOON, difficulty: 3, strokeCount: 6 },
  { id: 'nyo', hiragana: 'にょ', katakana: 'ニョ', romaji: 'nyo', category: KanaCategory.YOON, difficulty: 3, strokeCount: 6 },
  { id: 'hya', hiragana: 'ひゃ', katakana: 'ヒャ', romaji: 'hya', category: KanaCategory.YOON, difficulty: 3, strokeCount: 5 },
  { id: 'hyu', hiragana: 'ひゅ', katakana: 'ヒュ', romaji: 'hyu', category: KanaCategory.YOON, difficulty: 3, strokeCount: 5 },
  { id: 'hyo', hiragana: 'ひょ', katakana: 'ヒョ', romaji: 'hyo', category: KanaCategory.YOON, difficulty: 3, strokeCount: 5 },
  { id: 'mya', hiragana: 'みゃ', katakana: 'ミャ', romaji: 'mya', category: KanaCategory.YOON, difficulty: 3, strokeCount: 6 },
  { id: 'myu', hiragana: 'みゅ', katakana: 'ミュ', romaji: 'myu', category: KanaCategory.YOON, difficulty: 3, strokeCount: 6 },
  { id: 'myo', hiragana: 'みょ', katakana: 'ミョ', romaji: 'myo', category: KanaCategory.YOON, difficulty: 3, strokeCount: 6 },
  { id: 'rya', hiragana: 'りゃ', katakana: 'リャ', romaji: 'rya', category: KanaCategory.YOON, difficulty: 3, strokeCount: 5 },
  { id: 'ryu', hiragana: 'りゅ', katakana: 'リュ', romaji: 'ryu', category: KanaCategory.YOON, difficulty: 3, strokeCount: 5 },
  { id: 'ryo', hiragana: 'りょ', katakana: 'リョ', romaji: 'ryo', category: KanaCategory.YOON, difficulty: 3, strokeCount: 5 },
  { id: 'gya', hiragana: 'ぎゃ', katakana: 'ギャ', romaji: 'gya', category: KanaCategory.YOON, difficulty: 3, strokeCount: 9 },
  { id: 'gyu', hiragana: 'ぎゅ', katakana: 'ギュ', romaji: 'gyu', category: KanaCategory.YOON, difficulty: 3, strokeCount: 9 },
  { id: 'gyo', hiragana: 'ぎょ', katakana: 'ギョ', romaji: 'gyo', category: KanaCategory.YOON, difficulty: 3, strokeCount: 9 },
  { id: 'ja', hiragana: 'じゃ', katakana: 'ジャ', romaji: 'zya', category: KanaCategory.YOON, difficulty: 3, strokeCount: 8 },
  { id: 'ju', hiragana: 'じゅ', katakana: 'ジュ', romaji: 'zyu', category: KanaCategory.YOON, difficulty: 3, strokeCount: 8 },
  { id: 'jo', hiragana: 'じょ', katakana: 'ジョ', romaji: 'zyo', category: KanaCategory.YOON, difficulty: 3, strokeCount: 8 },
  { id: 'bya', hiragana: 'びゃ', katakana: 'ビャ', romaji: 'bya', category: KanaCategory.YOON, difficulty: 3, strokeCount: 7 },
  { id: 'byu', hiragana: 'びゅ', katakana: 'ビュ', romaji: 'byu', category: KanaCategory.YOON, difficulty: 3, strokeCount: 7 },
  { id: 'byo', hiragana: 'びょ', katakana: 'ビョ', romaji: 'byo', category: KanaCategory.YOON, difficulty: 3, strokeCount: 7 },
  { id: 'pya', hiragana: 'ぴゃ', katakana: 'ピャ', romaji: 'pya', category: KanaCategory.YOON, difficulty: 3, strokeCount: 7 },
  { id: 'pyu', hiragana: 'ぴゅ', katakana: 'ピュ', romaji: 'pyu', category: KanaCategory.YOON, difficulty: 3, strokeCount: 7 },
  { id: 'pyo', hiragana: 'ぴょ', katakana: 'ピョ', romaji: 'pyo', category: KanaCategory.YOON, difficulty: 3, strokeCount: 7 },
];
export const KANA_BY_CATEGORY = {
  [KanaCategory.SEION]: KANA_DATA.filter(k => k.category === KanaCategory.SEION),
  [KanaCategory.DAKUON]: KANA_DATA.filter(k => k.category === KanaCategory.DAKUON),
  [KanaCategory.HANDAKUON]: KANA_DATA.filter(k => k.category === KanaCategory.HANDAKUON),
  [KanaCategory.YOON]: KANA_DATA.filter(k => k.category === KanaCategory.YOON)
} as const;
export const KANA_BY_DIFFICULTY = {
  1: KANA_DATA.filter(k => k.difficulty === 1),
  2: KANA_DATA.filter(k => k.difficulty === 2),
  3: KANA_DATA.filter(k => k.difficulty === 3)
} as const;
export const CATEGORY_LABELS = {
  [KanaCategory.SEION]: {
    en: 'Seion (Clear Sounds)',
    zh: '清音'
  },
  [KanaCategory.DAKUON]: {
    en: 'Dakuon (Voiced Sounds)',
    zh: '浊音'
  },
  [KanaCategory.HANDAKUON]: {
    en: 'Handakuon (Semi-voiced)',
    zh: '半浊音'
  },
  [KanaCategory.YOON]: {
    en: 'Yoon (Contracted)',
    zh: '拗音'
  }
} as const;
